// automatically generated by the FlatBuffers compiler, do not modify

package org.learn.gossip.messages;

public final class EventType {
  private EventType() { }
  public static final byte LIVE = 0;
  public static final byte SUSPECT = 1;
  public static final byte FAILED = 2;

  public static final String[] names = { "LIVE", "SUSPECT", "FAILED", };

  public static String name(int e) { return names[e]; }
}

