// automatically generated by the FlatBuffers compiler, do not modify

package org.learn.gossip.messages;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class MembershipEvent extends Table {
  public static MembershipEvent getRootAsMembershipEvent(ByteBuffer _bb) { return getRootAsMembershipEvent(_bb, new MembershipEvent()); }
  public static MembershipEvent getRootAsMembershipEvent(ByteBuffer _bb, MembershipEvent obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; }
  public MembershipEvent __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public byte eventType() { int o = __offset(4); return o != 0 ? bb.get(o + bb_pos) : 0; }
  public MemberInfo member() { return member(new MemberInfo()); }
  public MemberInfo member(MemberInfo obj) { int o = __offset(6); return o != 0 ? obj.__assign(__indirect(o + bb_pos), bb) : null; }

  public static int createMembershipEvent(FlatBufferBuilder builder,
      byte eventType,
      int memberOffset) {
    builder.startObject(2);
    MembershipEvent.addMember(builder, memberOffset);
    MembershipEvent.addEventType(builder, eventType);
    return MembershipEvent.endMembershipEvent(builder);
  }

  public static void startMembershipEvent(FlatBufferBuilder builder) { builder.startObject(2); }
  public static void addEventType(FlatBufferBuilder builder, byte eventType) { builder.addByte(0, eventType, 0); }
  public static void addMember(FlatBufferBuilder builder, int memberOffset) { builder.addOffset(1, memberOffset, 0); }
  public static int endMembershipEvent(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
}

