// automatically generated by the FlatBuffers compiler, do not modify

package org.learn.gossip.messages;

public final class MessageType {
  private MessageType() { }
  public static final byte PING = 0;
  public static final byte PING_RES = 1;
  public static final byte ACK = 2;
  public static final byte NACK = 3;

  public static final String[] names = { "PING", "PING_RES", "ACK", "NACK", };

  public static String name(int e) { return names[e]; }
}

