// automatically generated by the FlatBuffers compiler, do not modify

package org.learn.gossip.messages;

public final class Payload {
  private Payload() { }
  public static final byte NONE = 0;
  public static final byte MemberInfo = 1;
  public static final byte MembershipEvent = 2;

  public static final String[] names = { "NONE", "MemberInfo", "MembershipEvent", };

  public static String name(int e) { return names[e]; }
}

